version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitor

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "64443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./htpasswd:/etc/nginx/.htpasswd
      - ./certs:/etc/nginx/certs
    depends_on:
      - prometheus
    networks:
      - monitor

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=https://${VPS_DOMAIN}:64443/
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitor

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    pid: "host"
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=0.0.0.0:9100'
    volumes:
      - /:/host:ro,rslave
    networks:
      - monitor

volumes:
  grafana-storage:
networks:
  monitor:
